### PR TITLE
Few QKD resources uploaded

### PR DESCRIPTION
**Pull request by ZexiXin**
Quasi-real-time QKD, Twin-field QKD, and Decoy QKD scheme with Chernoff Boundary check

### CODE REVIEW

**Comment by ZexiXin** [comment]
Also the newest version of timeline and the Gantt chart have been uploaded

**Comment by Vidmaster** [comment]
Can you please remove the PDF files and just share links with the team in Slack instead? Since those are journal articles that aren't licensed we can't be uploading them to a public Git repository.

**Comment by ZexiXin** [comment]
Ok, I will do that

**Comment by ZexiXin** [comment]
I have deleted those journals from the Resource folder. Please take a look at it

**Review by Vidmaster — APPROVED** [review]

**Pull request merged**
